language: python
sudo: false

branches:
  only:
    - stable
    - master

addons:
  hosts:
  - pocket.PiAP.local

matrix:
  include:
  - os: linux
    python:  "2.7"
    dist: trusty
  - os: linux
    python:  "3.3"
    dist: trusty
  - os: linux
    python:  "3.4"
    dist: trusty
  - os: linux
    python:  "3.5"
    dist: trusty
  - os: linux
    python:  "3.6"
  - os: linux
    dist: trusty
    python:  "3.5-dev" # 3.5 development branch
  - os: linux
    python:  "3.6-dev"
  - os: linux
    python:  "3.7-dev"
  - os: linux
    python: "pypy"  # PyPy2 2.5.0
  - os: linux
    python: "pypy3"
  - os: linux
    python:  "pypy-5.3.1"
  - os: linux
    python:  "nightly" # currently points to 3.6-dev
  - os: osx
    osx_image: xcode6.4
    language: generic
  - os: osx
    osx_image: xcode7.2
    language: generic
  - os: osx
    osx_image: xcode7.3
    language: generic
  - os: osx
    osx_image: xcode8
    language: generic
  - os: osx
    osx_image: xcode8.3
    language: generic
  - os: osx
    osx_image: xcode9
    language: generic
  allow_failure:
  - os: osx
    osx_image: xcode6.4
    language: generic
  - os: linux
    python:  "2.6"
  - os: linux
    python:  "3.2"
  - os: linux
    python: "pypy"
    dist: precise
  - os: linux
    python:  "pypy3"
  - os: linux
    python:  "pypy-5.3.1"

install:  "make init"

before_install:
  - if [ $TRAVIS_OS_NAME == osx ] ; then travis_retry brew tap homebrew/versions || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then travis_wait brew upgrade || travis_retry brew upgrade || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python2.6 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python26 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then travis_wait brew install python3 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.3 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py3.3 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.4 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python34 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py3.4 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.5 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python35 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py3.5 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.6 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python36 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py3.6 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python2.7 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python27 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py2.7 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.6 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.7 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install coverage $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install codecov $INSTALL || true ; fi
  - travis_retry pip install tox || pip install tox || true ;
  - travis_retry pip install coverage || true ;
  - travis_retry pip install codecov || true ;
  - travis_retry python -m pip install coverage || python -m pip install coverage || true ;
  - travis_retry python -m pip install codecov || python -m pip install codecov || true ;
  - travis_retry python3 -m pip install tox || python3 -m pip install tox || true ;
  - travis_retry python3 -m pip install coverage || python3 -m pip install coverage || true ;
  - travis_retry python3 -m pip install codecov || python3 -m pip install codecov || true ;
  - travis_retry python3 -m pip install -r requirements.txt || python3 -m pip install -r requirements.txt || true ;

script:
  - make clean ;
  - if [ $TRAVIS_OS_NAME == osx ] ; then echo "SKIP make test" ; else make test || exit $? ; fi ;
  - if [ $TRAVIS_OS_NAME == osx ] ; then echo "SKIP codecov" ; else codecov || exit $? ; fi ;
  - travis_retry pip install python-coveralls 2>/dev/null || python3 -m pip install python-coveralls || true ;
  - coveralls 2>/dev/null || true
  - travis_retry pip uninstall -y python-coveralls || travis_retry python3 -m pip uninstall -y python-coveralls || true
  - travis_retry pip uninstall -y PyYAML || travis_retry python3 -m pip uninstall -y PyYAML || true
  - make clean || exit $? ; 
  - make test-tox || exit $? ;
  - cp -vf .coverage ".coverall.Lasting.45678.12345" 2>/dev/null || true
  - make clean ;
  - mv -vf ".coverall.Lasting.45678.12345" .coverage 2>/dev/null || true
  - if [ $TRAVIS_OS_NAME == osx ] ; then true ; wait ; else pip install --upgrade -e git+https://github.com/reactive-firewall/PiAP-python-tools.git@${TRAVIS_PULL_REQUEST_SHA:-${TRAVIS_COMMIT}}#egg=piaplib ; fi ; wait ;

after_success:
  - coverage combine || true
  - codecov || true
  - travis_retry python3 -m pip install python-coveralls || python3 -m pip install python-coveralls || true ;
  - coveralls 2>/dev/null || true
  - travis_retry python -m pip uninstall -y PyYAML || travis_retry python3 -m pip uninstall -y PyYAML || true
  - if [ $TRAVIS_OS_NAME == osx ] ; then true ; wait ; else coverage run -p -m piaplib.pocket pku upgrade --upgrade-all || true ; fi ;
  - if [ $TRAVIS_OS_NAME == osx ] ; then echo "SKIP codecov" ; else codecov || exit $? ; fi ;

