language: python
sudo: false

branches:
  only:
    - stable
    - master

addons:
  hosts:
  - pocket.PiAP.local

matrix:
  include:
  - os: linux
    python: "2.6"
  - os: linux
    python:  "2.7"
  - os: linux
    python:  "3.2"
  - os: linux
    python:  "3.3"
  - os: linux
    python:  "3.4"
  - os: linux
    python:  "3.5"
  - os: linux
    python:  "3.6"
  - os: linux
    python:  "3.5-dev" # 3.5 development branch
  - os: linux
    python:  "nightly" # currently points to 3.6-dev
  - os: osx
    osx_image: xcode6.4
    language: generic
  - os: osx
    osx_image: xcode7.2
    language: generic
  - os: osx
    osx_image: xcode7.3
    language: generic
  - os: osx
    osx_image: xcode8
    language: generic
  - os: osx
    osx_image: xcode8.3
    language: generic

jobs:
  include:
    - stage: test
      install: "make init"
      before_install:
        - true
      script:
        - make clean
        - if [ $TRAVIS_OS_NAME == osx ] ; then true ; wait ; else make test ; fi ; exit $? ;
    - # stage name not required, will continue to use `test`
      install: "make init"
      before_install:
        - if [ $TRAVIS_OS_NAME == osx ] ; then brew upgrade || true ; fi
        - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python2.6 $INSTALL || true ; fi
        - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.4 $INSTALL || true ; fi
        - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.5 $INSTALL || true ; fi
        - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python2.7 $INSTALL || true ; fi
        - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.6 $INSTALL || true ; fi
        - if [ $TRAVIS_OS_NAME == osx ] ; then pip install tox || true ; fi
      script:
        - make clean
        - make test-tox ; exit $? ;
    - stage: deploy
      install: "make init"
      before_install:
        - if [ $TRAVIS_OS_NAME == osx ] ; then brew upgrade || true ; fi
        - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python2.6 $INSTALL || true ; fi
        - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.4 $INSTALL || true ; fi
        - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.5 $INSTALL || true ; fi
        - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python2.7 $INSTALL || true ; fi
        - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.6 $INSTALL || true ; fi
        - if [ $TRAVIS_OS_NAME == osx ] ; then pip install tox || true ; fi
	  script:
        - make clean
        - if [ $TRAVIS_OS_NAME == osx ] ; then true ; wait ; else make test ; fi ;
        - if [ $TRAVIS_OS_NAME == osx ] ; then true ; wait ; else pip install --upgrade -e https://raw.githubusercontent.com/reactive-firewall/PiAP-python-tools.git@${TRAVIS_PULL_REQUEST_SHA:-TRAVIS_COMMIT}#egg=piaplib ; fi ; exit $? ;

