#! /bin/bash

# exit fast if command is missing
test -x /usr/bin/spellintian || exit 0 ;

THE_TEMP_FILE="/tmp/swapfile_spellcheck_${RANDOM}.tmp.txt" ;
( (spellintian "${@:-./**/*}" 2>/dev/null | fgrep -v "(duplicate word)" | fgrep " -> ") & (spellintian "${@:-./*}" 2>/dev/null | fgrep -v "(duplicate word)" | fgrep " -> ") & (spellintian "${@:-./**/**/*}"  2>/dev/null | fgrep -v "(duplicate word)" | fgrep " -> ") ) | sort -h | uniq | tee -a ${THE_TEMP_FILE:-/dev/null} ;
wait ;
THECOUNT=$( (wc -l ${THE_TEMP_FILE} 2>/dev/null || echo 0) | cut -d\  -f 1 ) ;
EXIT_CODE=${THECOUNT} ;
if [[ ("${THECOUNT}" -le 1) ]] ; then
	EXIT_CODE=0 ;
	echo "OK: Found no detected spelling errors." ;
else
	echo "FAIL: Found ${THECOUNT:-many} spelling errors." ;
fi
rm -f ${THE_TEMP_FILE} 2>/dev/null >> /dev/null || true ;
wait ;
exit ${EXIT_CODE:255} ;
