version: 2
jobs:
  build:
    working_directory: ~/PiAP-python-tools
    docker:
      - image: circleci/python:3.5.3
        environment:
          CI: cicleci
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run:
          name: "fetch and pull"
          command: |
            git fetch && git pull --all || true
      - run:
          name: "install coverage attempt"
          command: |
            python3 -m pip install --user coverage || true
      - run:
          name: "install flake8 attempt"
          command: |
            python3 -m pip install --user flake8 || true
      - run:
          shell: /bin/bash
          name: "clean up for test"
          command: |
            make clean
      - run:
          shell: /bin/bash
          name: "Unit Tests"
          command: |
            make test
      - run:
          name: "clean up from test"
          command: |
            make clean
      - run:
          shell: /bin/bash
          name: "check code style"
          command: |
            make test-style || python3 -m flake8 --ignore=W191,W391 --max-line-length=100 --verbose --count --config=.flake8.ini --max-complexity=15
      - run:
          name: "clean up when done"
          command: |
            make clean
destination: build
