version: 2
jobs:
  build:
    working_directory: ~/PiAP-python-tools
    docker:
      - image: circleci/python:3.5.3
        environment:
          CI: cicleci
          DEBIAN_FRONTEND: noninteractive
          LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          name: "fetch and pull"
          command: |
            git fetch && git pull --all || true
      - run:
          shell: /bin/bash
          name: "install depends attempt"
          command: |
            python3 -m pip install --user -r ./requirements.txt || true
      - run:
          shell: /bin/bash
          name: "install coverage attempt"
          command: |
            python3 -m pip install --user coverage || true
      - run:
          name: "install flake8 attempt"
          command: |
            python3 -m pip install --user flake8 || true
      - run:
          shell: /bin/bash
          name: "prep dir for test part 1"
          command: |
            sudo mkdir -p -m 755 "/opt/PiAP/" || true
      - run:
          shell: /bin/bash
          name: "prep dir for test part 2"
          command: |
            sudo chown -v circleci "/opt/PiAP/"
      - run:
          shell: /bin/bash
          name: "prep dir for test"
          command: |
            mkdir -p -m 755 "/opt/PiAP/hostapd_actions/"
      - run:
          shell: /bin/bash
          name: "install mocking cmd for test"
          command: |
            cp -vf ./tests/mock/clients /opt/PiAP/hostapd_actions/clients
      - run:
          shell: /bin/bash
          name: "clean up for test"
          command: |
            make clean
      - run:
          shell: /bin/bash
          name: "Unit Tests"
          command: |
            make test
      - run:
          shell: /bin/bash
          name: "clean up from test"
          command: |
            make clean
      - run:
          shell: /bin/bash
          name: "check code style and spelling"
          command: |
            make test-style || python3 -m flake8 --ignore=W191,W391,W504,W605 --max-line-length=100 --verbose --count --config=.flake8.ini --max-complexity=15
      - run:
          shell: /bin/bash
          name: "clean up when done"
          command: |
            make clean
destination: build
