version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5.3
    environment:
      CI: cicleci
      DEBIAN_FRONTEND: noninteractive
      LANG: en_US.UTF-8
      LC_CTYPE: en_EN.UTF-8
    working_directory: ~/PiAP-python-tools
    steps:
      - checkout
      - run:
          name: "fetch and pull"
          command: |
            git fetch && git pull --all || true
      - run:
          shell: /bin/bash
          name: "install depends attempt"
          command: |
            python3 -m pip install --user -r ./requirements.txt || true
      - run:
          shell: /bin/bash
          name: "install coverage attempt"
          command: |
            python3 -m pip install --user coverage || true
      - run:
          name: "install flake8 attempt"
          command: |
            python3 -m pip install --user flake8 || true
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/PiAP-python-tools

  test:
    docker:
      - image: circleci/python:3.5.3
    environment:
      CI: cicleci
      DEBIAN_FRONTEND: noninteractive
      LANG: en_US.UTF-8
      LC_CTYPE: en_EN.UTF-8
    working_directory: ~/PiAP-python-tools
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          shell: /bin/bash
          name: "Prep env for test"
          command: |
            sudo mkdir -p -m 755 "/opt/PiAP/" || true
            sudo chown -v circleci "/opt/PiAP/"
            mkdir -p -m 755 "/opt/PiAP/hostapd_actions/"
            cp -vf ./tests/mock/clients /opt/PiAP/hostapd_actions/clients
      - run:
          shell: /bin/bash
          name: "clean up for test"
          command: |
            make clean
      - run:
          shell: /bin/bash
          name: "Unit Tests"
          command: |
            make test
      - run:
          shell: /bin/bash
          name: "clean up from test"
          command: |
            make clean
      - run:
          shell: /bin/bash
          name: "check code style and spelling"
          command: |
            make test-style || python3 -m flake8 --ignore=W191,W391,W504,W605 --max-line-length=100 --verbose --count --config=.flake8.ini --max-complexity=15
      - run:
          shell: /bin/bash
          name: "clean up when done"
          command: |
            make clean

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
